### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by clocad** [mkara44/liveportrait_talker#5]
first it gave Error saying there is no numpy, so i did pip install numpy, then pip install requirements. Then when running inference command following error: 

Config File is loaded succesfully!
Traceback (most recent call last):
  File "D:\liveportrait_talker\inference.py", line 78, in <module>
    main(args)
  File "D:\liveportrait_talker\inference.py", line 23, in main
    preprocess = Preprocess(device=cfg.device,
  File "D:\liveportrait_talker\src\modules\preprocess.py", line 28, in __init__
    self.sd_prep = SadTalkerPreprocess(device=device,
  File "D:\liveportrait_talker\src\utils\preprocess\sadtalker_preprocess.py", line 20, in __init__
    self.detector = init_alignment_model('awing_fan', device=device, model_rootpath=model_path)
  File "D:\liveportrait_talker\src\utils\preprocess\helper.py", line 147, in init_alignment_model
    model.load_state_dict(torch.load(model_path, map_location=device)['state_dict'], strict=True)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1272, in _legacy_load
    result = unpickler.load()
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1205, in persistent_load
    obj = restore_location(obj, location)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1313, in restore_location
    return default_restore_location(storage, map_location)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 390, in default_restore_location
    result = fn(storage, location)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 307, in _mps_deserialize
    return obj.mps()
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\storage.py", line 144, in mps
    return torch.UntypedStorage(self.size(), device="mps").copy_(self, False)
RuntimeError: torch.UntypedStorage(): Storage device not recognized: mps

**Comment by mkara44** [comment]
You should update device type in config.yaml (inference.device). If you are using gpu you have to set device as cuda, if not you have to set as cpu. In default, i set as mps which is for macbook.
